name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.4.0
    - name: install
      run: npm ci
    - name: prettier
      run: npm run prettier
    - name: eslint
      run: npm run eslint
    - name: stylelint
      run: npm run stylelint
    - name: tsc
      run: npm run type-check
